RESEARCH NOTES -- DO NOT MERGE
Failing spec for testing how catalog expectations in function specs should look
like. This leads to the following error:

$ rbenv exec bundle exec rspec spec/functions/catalogue_spec.rb
.F.

Failures:

  1) split rspec group should be able to match resources in the catalogue
     Failure/Error: expect(catalogue).not_to contain_package('packagename')
     NoMethodError:
       undefined method `call' for #<Puppet::Resource::Catalog:0x00000001f97e40>
     # ./lib/rspec-puppet/matchers/create_generic.rb:82:in `matches?'
     # ./spec/functions/catalogue_spec.rb:10:in `block (3 levels) in <top (required)>'

Finished in 0.05395 seconds
3 examples, 1 failure

Failed examples:

rspec ./spec/functions/catalogue_spec.rb:9 # split rspec group should be able to match resources in the catalogue
$

as a workaround, this can be written as `expect(lambda { catalogue }).to ...`,
but that looks aweful. In rspec, the simple fix would be making
create_generic.rb:82 conditional on `catalogue` being a lambda, but that
doesn't sound too right, either.

Further inspection revealed, that some matchers use `catalogue.call` to get to
the actual catalogue, but the FunctionExampleGroup does not provide a lambda.

Note how the additional spec in spec/classes/test_api.rb does NOT fail.

From my (very limited) understanding of rspec internals, the thing passed to
`expect()` should not be modified before being passed onto the matchers?